/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'
import { Route as AdminCategoriesRouteImport } from './routes/admin/categories'
import { Route as AdminIncompleteOrdersRouteImport } from './routes/admin/incomplete-orders'
import { Route as AdminLandingPagesRouteImport } from './routes/admin/landing-pages'
import { Route as AdminOrdersRouteImport } from './routes/admin/orders'
import { Route as AdminProductsRouteImport } from './routes/admin/products'
import { Route as LSlugRouteImport } from './routes/l.$slug'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as AdminLandingPagesSlugEditRouteImport } from './routes/admin/landing-pages.$slug.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIncompleteOrdersRoute = AdminIncompleteOrdersRouteImport.update({
  id: '/incomplete-orders',
  path: '/incomplete-orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLandingPagesRoute = AdminLandingPagesRouteImport.update({
  id: '/landing-pages',
  path: '/landing-pages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const LSlugRoute = LSlugRouteImport.update({
  id: '/l/$slug',
  path: '/l/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLandingPagesSlugEditRoute =
  AdminLandingPagesSlugEditRouteImport.update({
    id: '/$slug/edit',
    path: '/$slug/edit',
    getParentRoute: () => AdminLandingPagesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/incomplete-orders': typeof AdminIncompleteOrdersRoute
  '/admin/landing-pages': typeof AdminLandingPagesRouteWithChildren
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/l/$slug': typeof LSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/landing-pages/$slug/edit': typeof AdminLandingPagesSlugEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/incomplete-orders': typeof AdminIncompleteOrdersRoute
  '/admin/landing-pages': typeof AdminLandingPagesRouteWithChildren
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/l/$slug': typeof LSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin': typeof AdminIndexRoute
  '/admin/landing-pages/$slug/edit': typeof AdminLandingPagesSlugEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/incomplete-orders': typeof AdminIncompleteOrdersRoute
  '/admin/landing-pages': typeof AdminLandingPagesRouteWithChildren
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/l/$slug': typeof LSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/landing-pages/$slug/edit': typeof AdminLandingPagesSlugEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/analytics'
    | '/admin/categories'
    | '/admin/incomplete-orders'
    | '/admin/landing-pages'
    | '/admin/orders'
    | '/admin/products'
    | '/l/$slug'
    | '/product/$slug'
    | '/admin/'
    | '/admin/landing-pages/$slug/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/analytics'
    | '/admin/categories'
    | '/admin/incomplete-orders'
    | '/admin/landing-pages'
    | '/admin/orders'
    | '/admin/products'
    | '/l/$slug'
    | '/product/$slug'
    | '/admin'
    | '/admin/landing-pages/$slug/edit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/analytics'
    | '/admin/categories'
    | '/admin/incomplete-orders'
    | '/admin/landing-pages'
    | '/admin/orders'
    | '/admin/products'
    | '/l/$slug'
    | '/product/$slug'
    | '/admin/'
    | '/admin/landing-pages/$slug/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LSlugRoute: typeof LSlugRoute
  ProductSlugRoute: typeof ProductSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/incomplete-orders': {
      id: '/admin/incomplete-orders'
      path: '/incomplete-orders'
      fullPath: '/admin/incomplete-orders'
      preLoaderRoute: typeof AdminIncompleteOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/landing-pages': {
      id: '/admin/landing-pages'
      path: '/landing-pages'
      fullPath: '/admin/landing-pages'
      preLoaderRoute: typeof AdminLandingPagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/l/$slug': {
      id: '/l/$slug'
      path: '/l/$slug'
      fullPath: '/l/$slug'
      preLoaderRoute: typeof LSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/landing-pages/$slug/edit': {
      id: '/admin/landing-pages/$slug/edit'
      path: '/$slug/edit'
      fullPath: '/admin/landing-pages/$slug/edit'
      preLoaderRoute: typeof AdminLandingPagesSlugEditRouteImport
      parentRoute: typeof AdminLandingPagesRoute
    }
  }
}

interface AdminLandingPagesRouteChildren {
  AdminLandingPagesSlugEditRoute: typeof AdminLandingPagesSlugEditRoute
}

const AdminLandingPagesRouteChildren: AdminLandingPagesRouteChildren = {
  AdminLandingPagesSlugEditRoute: AdminLandingPagesSlugEditRoute,
}

const AdminLandingPagesRouteWithChildren =
  AdminLandingPagesRoute._addFileChildren(AdminLandingPagesRouteChildren)

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminIncompleteOrdersRoute: typeof AdminIncompleteOrdersRoute
  AdminLandingPagesRoute: typeof AdminLandingPagesRouteWithChildren
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminIncompleteOrdersRoute: AdminIncompleteOrdersRoute,
  AdminLandingPagesRoute: AdminLandingPagesRouteWithChildren,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LSlugRoute: LSlugRoute,
  ProductSlugRoute: ProductSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
